source 'https://rubygems.org'

gem 'rails', '3.2.14'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

#Gemfile
group :development, :test do
  gem 'pry-rails'           # Causes rails console to open pry
                            # https://github.com/rweng/pry-rails
  gem 'pry-debugger'        # Adds step, next, finish, and continue commands and breakpoints
                            # https://github.com/nixme/pry-debugger
  gem 'pry-stack_explorer'  # Navigate the call-stack
                            # https://github.com/pry/pry-stack_explorer
  gem 'annotate'            # Annotate all your models, tests, fixtures, and factories
                            # https://github.com/ctran/annotate_models
  gem 'quiet_assets'        # Turns off the Rails asset pipeline log
                            # https://github.com/evrone/quiet_assets
  gem 'better_errors'       # Replaces the standard Rails error page with a much better and more useful error page
                            # https://github.com/charliesome/better_errors
  gem 'binding_of_caller'   # Advanced features for better_errors advanced features (REPL, local/instance variable inspection, pretty stack frame names)
                            # https://github.com/banister/binding_of_caller
  gem 'meta_request'        # Supporting gem for Rails Panel (Google Chrome extension for Rails development).
                            # https://github.com/dejan/rails_panel/tree/master/meta_request
  gem 'rails-erd'           # Diagrams your models. NOTE! $ brew install graphviz
                            # https://github.com/voormedia/rails-erd
  gem 'awesome_print'       # Pretty print your Ruby objects in full color and with proper indentation
                            # https://github.com/michaeldv/awesome_print
end


gem "rspec-rails", :group => [:test, :development]
gem "guard-rspec", :group => [:test, :development]
gem "capybara", :group => [:test, :development]
gem "selenium-webdriver", :group => [:test, :development]
gem "database_cleaner", :group => [:test, :development]
gem "launchy", :group => [:test, :development]
gem "jasmine", :group => [:test, :development]
gem "pry-rails", :group => [:test, :development]
gem "pry-debugger", :group => [:test, :development]
gem "pry-stack_explorer", :group => [:test, :development]
gem "annotate", :group => [:test, :development]
gem "quiet_assets", :group => [:test, :development]
gem "binding_of_caller", :group => [:test, :development]
gem "meta_request", :group => [:test, :development]
gem "rails-erd", :group => [:test, :development]
gem "awesome_print", :group => [:test, :development]
gem "terminal-notifier-guard", :group => [:test, :development]
gem "simplecov", :require => false, :group => :test
gem "thin"