source 'https://rubygems.org'

gem 'rails', '3.2.14'
ruby "1.9.3"

gem 'pg'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development do
  gem 'pry-rails'
end
