# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Student.create(name: "Alex Hint", image_url: "http://m.c.lnkd.licdn.com/media/p/5/000/2cb/06d/132b669.jpg", email: "alex.hint.ah@gmail.com")
Student.create(name: "Amy Ruan", image_url: "https://scontent-b-pao.xx.fbcdn.net/hphotos-ash4/254648_617146790825_5761000_n.jpg", email: "nyc.amy@gmail.com")
Student.create(name: "Ana Giraldo-Wingler ", image_url: "https://generalassembly.wufoo.com/cabinet/z4p1w7/o1vr6Sfw3vI%3D/circleimage5.png", email: "agiraldow@gmail.com")
Student.create(name: "Cooper Mayne", image_url: "http://loopacoop.com/GA/face.jpg", email: "coopermayne@gmail.com")
Student.create(name: "Diego Palma", image_url: "http://intothewildproyect.com/img/photo.jpg", email: "dppalma@gmail.com")
Student.create(name: "Edward Shin", image_url: "https://scontent-b-pao.xx.fbcdn.net/hphotos-prn1/16170_669084572267_6465149_n.jpg", email: "eshin0910@gmail.com")
Student.create(name: "Enoch Riese", image_url: "https://scontent-a-pao.xx.fbcdn.net/hphotos-ash2/582269_10200103965106389_620401206_n.jpg", email: "enoch.riese@gmail.com")
Student.create(name: "Harrison Powers ", image_url: "http://harrypowers.it/images/harrison_powers.png", email: "harrisonpowers@gmail.com")
Student.create(name: "Jaclyn Jimenez", image_url: "https://scontent-b-pao.xx.fbcdn.net/hphotos-prn1/1174554_10200812779545275_96540317_n.jpg", email: "jaclynejimenez@gmail.com")
Student.create(name: "James Rothpearl", image_url: "https://scontent-a-lga.xx.fbcdn.net/hphotos-ash3/q74/s720x720/1259_2035167003492_2052351865_n.jpg", email: "jrothpearl@gmail.com")
Student.create(name: "Jimmy Davis", image_url: "http://i.imgur.com/jHhVq5y.png", email: "jamesmdavis5@gmail.com")
Student.create(name: "Jonathan Leung", image_url: "http://cl.ly/image/3S1L191V3z32/Untitled%206.png", email: "me@jonl.org")
Student.create(name: "Jorge Colindres", image_url: "http://goo.gl/qejElo", email: "jorge.e.colindres@gmail.com")
Student.create(name: "Joshua Oynick", image_url: "https://generalassembly.wufoo.com/cabinet/z4p1w7/VLWfWjaun1c%3D/josh_oynick__picture_2.png", email: "oynickj@gmail.com")
Student.create(name: "Katherine Santiago", image_url: "https://si0.twimg.com/profile_images/2449491240/image.jpg", email: "santiago.kat@gmail.com")
Student.create(name: "Matt Lucas", image_url: "http://i710.photobucket.com/albums/ww107/ml242/PhotoBoothfromInstallation_zps87804a54.jpg", email: "mattlucas@gmail.com")
Student.create(name: "Matthew Korporaal", image_url: "http://i.imgur.com/7ExAI1Z.jpg", email: "matthew.korporaal@gmail.com")
Student.create(name: "Morgan Neiman", image_url: "https://scontent-b-pao.xx.fbcdn.net/hphotos-ash4/1005424_10200808000896420_398916581_n.jpg", email: "quackhouse@me.com")
Student.create(name: "Natasha Green", image_url: "http://m.c.lnkd.licdn.com/mpr/pub/image-W29PMYSOvW5p_rceCNp6ulw1_kIx0Nppd2v9fMLO_psLr8CiW299_zkO_0fMr0X6-jzg/natasha-green.jpg", email: "greennatasha@aol.com")
Student.create(name: "Quin Cogdell ", image_url: "http://i.imgur.com/KmvQlnq.jpg", email: "quincogdell@gmail.com")
Student.create(name: "Tom Metzger", image_url: "https://generalassembly.wufoo.com/cabinet/z4p1w7/el6gWFjv2xM%3D/img_7517.jpg", email: "metzgert@gmail.com")
Student.create(name: "Travis Vanderhoop", image_url: "http://b.vimeocdn.com/ps/309/202/3092028_300.jpg", email: "vanderhoop@me.com")
Student.create(name: "Will Smith", image_url: "http://f.cl.ly/items/25240Q0N2y1e2M343P2H/IMG_1046.JPG", email: "will.smith@preplaysports.com")
